### ISSUE TITLE
Do we know if Portworx 2.0.2.3 works with Velero (Ark) v11?

### ISSUE THREAD

**Issue by cormachogan** [portworx/ark-plugin#7] opened 2019-03-25 08:36 UTC
Looking at Heptio Velero (previously Ark) and Portworx, and having a few issues with local snapshots.

$ /opt/pwx/bin/pxctl -v
pxctl version 2.0.2.3-c186a87 (OCI)

$ velero version
Client:
   Version: v0.11.0
   Git commit: ab2fc65c02ecdcb9bb1690e3afe67a3b3196aebc
Server:
   Version: v0.11.0

When we try to take a backup, we see this error thrown consistently in the logs:

time=“2019-03-22T13:44:50Z” level=error msg=“backup failed” controller=backup error=“[error taking snapshot of volume: rpc error: code = Unknown desc = Invalid name for snapshot _pvc-b4d5c145-4c95-11e9-aadf-0050568f6f18 - volume name \“_pvc-b4d5c145-4c95-11e9-aadf-0050568f6f18\” contains illegal characters, only \“[a-zA-Z0-9][a-zA-Z0-9_.-]*\” are allowed, error taking snapshot of volume: rpc error: code = Unknown desc = Invalid name for snapshot _pvc-d4e64420-4c95-11e9-aadf-0050568f6f18 - volume name \“_pvc-d4e64420-4c95-11e9-aadf-0050568f6f18\” contains illegal characters, only \“[a-zA-Z0-9][a-zA-Z0-9_.-]*\” are allowed, error taking snapshot of volume: rpc error: code = Unknown desc = Invalid name for snapshot _pvc-ea6897b6-4c95-11e9-aadf-0050568f6f18 - volume name \“_pvc-ea6897b6-4c95-11e9-aadf-0050568f6f18\” contains illegal characters, only \“[a-zA-Z0-9][a-zA-Z0-9_.-]*\” are allowed, error taking snapshot of volume: rpc error: code = Unknown desc = Invalid name for snapshot _pvc-f1e79424-4a4b-11e9-aadf-0050568f6f18 - volume name \“_pvc-f1e79424-4a4b-11e9-aadf-0050568f6f18\” contains illegal characters, only \“[a-zA-Z0-9][a-zA-Z0-9_.-]*\” are allowed, error taking snapshot of volume: rpc error: code = Unknown desc = Invalid name for snapshot _pvc-e9109e0d-4a59-11e9-aadf-0050568f6f18 - volume name \“_pvc-e9109e0d-4a59-11e9-aadf-0050568f6f18\” contains illegal characters, only \“[a-zA-Z0-9][a-zA-Z0-9_.-]*\” are allowed]” key=velero/local-snapshot-backup4 logSource=“pkg/controller/backup_controller.go:202”

I see an underscore prefixing all the “volume names” -- has the portworx plugin been updated to be compatible with v0.11?

**Comment by disrani-px** [comment] 2019-03-25 15:38
I think the issue is that Velero is adding an extra space after the tag `ark.heptio.com/backup` that we use as the prefix of the snapshot. So the snapshot name becomes `snapshot _pvc-d4e64420-4c95-11e9-aadf-0050568f6f18` which is illegal

**Comment by cormachogan** [comment] 2019-03-25 15:51
Thanks - I will feed this back to them.

**Comment by disrani-px** [comment] 2019-03-25 16:16
I will also trim the spaces in the plugin to avoid hitting such issues in the future

**Comment by disrani-px** [comment] 2020-02-03 18:49
Fixed with #8

**Closed as completed by disrani-px** 2020-02-03 18:49 UTC
